<?php
/**
 * cms-nckh - Input.php
 *
 * Initial version by: linhphung
 * Initial version create on : 18/08/2019
 *
 */

namespace CustomModule\BuildingManager\Ui\Component\Form\Element;


class Input extends \Magento\Ui\Component\Form\Element\Input
{
    public function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
        $config = $this->getData('config');
        if (isset($config['dataScope']) && $config['dataScope'] == 'datecreate') {
            $config['default'] = date('Y-m-d');
            $this->setData('config', (array)$config);
        }

        if (isset($config['dataScope']) && $config['dataScope'] == 'installdate') {
            $config['default'] = date('Y-m-d');
            $this->setData('config', (array)$config);
        }
        if (isset($config['dataScope']) && $config['dataScope'] == 'modifydate') {
            $config['default'] = date('Y-m-d');
            $this->setData('config', (array)$config);
        }


    }

}