<?php
/**
 * cms-nckh - Input.php
 *
 * Initial version by: linhphung
 * Initial version create on : 19/08/2019
 *
 */

namespace CustomModule\BuildingManager\Ui\Component\Form\Element\Room;


class Input extends \Magento\Ui\Component\Form\Element\Input
{
    public function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
        $config = $this->getData('config');
        if (isset($config['dataScope']) && $config['dataScope'] == 'image') {
           /* $config['default'] = date('Y-m-d');
            $this->setData('config', (array)$config);*/
        }

    }

    public function prepareDataSource(array $dataSource){
        $a = $dataSource;
    }

    public function getData($key = '', $index = null)
    {
        return parent::getData($key, $index); // TODO: Change the autogenerated stub
    }

}